DIST_NAME = artist

SCRIPT_FILES = \
	src/carousel/index.ts \
	src/carousel/ActionCarousel.ts \
	src/carousel/Carousel.ts \
	src/carousel/CarouselAction.ts \
	src/index.ts \
	src/demo/diagonalBlockDemo.ts \
	src/demo/viewportDom.ts \
	src/demo/carouselGraph.ts \
	src/demo/logo.ts \
	src/demo/interact.ts \
	src/demo/html.ts \
	src/demo/block3d.ts \
	src/demo/stringtree.ts \
	src/demo/artist.ts \
	src/demo/carousel.ts \
	src/demo/blockrandom.ts \
	src/demo/blockdom.ts \
	src/demo/viewport.ts \
	src/demo/graphpainter.ts \
	src/demo/dom.ts \
	src/demo/block.ts \
	src/demo/weboverlay.ts \
	src/demo/block2d.ts \
	src/demo/blockartist/BlockArtist2D.ts \
	src/demo/blockartist/BlockArtist3D.ts \
	src/demo/blockartist/BlockArtistDOM.ts \
	src/glsl.d.ts \
	src/graphpainter/GraphPainterAnalytics.ts \
	src/graphpainter/PaintRun.ts \
	src/graphpainter/index.ts \
	src/graphpainter/PaintGroup.ts \
	src/graphpainter/GraphPainter.ts \
	src/graphpainter/RenderArtist.ts \
	src/graphpainter/NodeRenderData.ts \
	src/navport/index.ts \
	src/navport/NavportMouseController.ts \
	src/navport/NavportCursor.ts \
	src/navport/NavportKeyController.ts \
	src/navport/displaymode/single.ts \
	src/navport/displaymode/fit.ts \
	src/navport/displaymode/fixed.ts \
	src/navport/displaymode/fullscreen.ts \
	src/navport/displaymode/menuless.ts \
	src/navport/displaymode/split.ts \
	src/navport/NavportWebOverlay.ts \
	src/navport/Navport.ts \
	src/navport/CameraFilter.ts \
	src/navport/InputController.ts \
	src/render/index.ts \
	src/render/render.ts \
	src/render/showGraph.ts \
	src/dom/index.ts \
	src/dom/DOMContent.ts \
	src/dom/DOMPainter.ts \
	src/artist/paintNodeBounds.ts \
	src/artist/Painted.ts \
	src/artist/index.ts \
	src/artist/paintNodeLines.ts \
	src/artist/fromNode.ts \
	src/artist/Artist.ts \
	src/artist/PaintedNode.ts \
	src/artist/BasicPainted.ts \
	src/artist/computeInnerPos.ts \
	src/artist/freezer/index.ts \
	src/artist/freezer/FreezerCache.ts \
	src/artist/freezer/Freezable.ts \
	src/artist/freezer/Freezer.ts \
	src/artist/freezer/FrozenNode.ts \
	src/artist/freezer/FrozenNodeFragment.ts \
	src/artist/freezer/FreezerSlot.ts \
	src/artist/freezer/FreezerRow.ts \
	src/artist/freezer/FreezerSlice.ts \
	src/artist/PaintedCaret.ts \
	src/artist/NodeValues.ts \
	src/artist/interact/index.ts \
	src/artist/interact/Interaction.ts \
	src/artist/interact/chainTab.ts \
	src/artist/interact/Interactive.ts \
	src/artist/applyTransform.ts \
	src/block/BlockPalette.ts \
	src/block/BlockNode.ts \
	src/block/BlockScene.ts \
	src/block/index.ts \
	src/block/TextEdit.ts \
	src/block/BlockArtist.ts \
	src/block/Block.ts \
	src/block/DefaultBlockPalette.ts \
	src/block/BlockType.ts \
	src/block/BlockStyle.ts \
	src/block/BlockCaret.ts \
	src/block/Label.ts \
	src/block/DefaultBlockScene.ts \
	src/demo.ts \
	test/test.ts

EXTRA_SCRIPTS = \
	src/artist/freezer/Freezer_VertexShader.glsl \
	src/artist/freezer/Freezer_FragmentShader.glsl

include ./Makefile.microproject
